- block: #MariabDB
    - name: Install requirments for MariaDB
      apt:
        name: [
            software-properties-common,
            dirmngr
        ]
    - name: Add MariDB apt key
      apt_key:
        url: https://mariadb.org/mariadb_release_signing_key.asc
    - name: "Add MariaDB repository version 10.5 for Debian {{ ansible_distribution_major_version }} ({{ ansible_distribution_release }})"
      apt_repository:
        repo: 'deb [arch=amd64] http://mariadb.mirror.triple-it.nl/repo/10.5/debian {{ ansible_distribution_release }} main'
    - name: Install MariaDB
      apt: name=mariadb-server